spring.application.name=SpringEcom

spring.datasource.url=jdbc:mysql://localhost:3306/springEcom
spring.datasource.username=root
spring.datasource.password=hey_mysql04!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
